[package]
name = "syncmiru-client"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-shell = "2.0.0-beta"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

keyring = "2.3.2"
rust-ini = "0.21.0"
dirs = "5.0.1"
sys-locale = "0.3.1"
thiserror = "1.0.58"
anyhow = "1.0.81"
tauri-plugin-theme = "0.4.0"
rust-i18n = "3.0.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "windef"] }

[target.'cfg(all(target_family = "unix", not(target_os = "macos")))'.dependencies]
x11rb = { version = "0.13.0"}