[package]
name = "syncmiru-srv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
anyhow = "1.0.81"
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres", "migrate" ] }
axum = "0.7.5"
axum-client-ip = "0.5.1"
socketioxide = { version = "0.12.0", features = ["state"] }
log = "0.4.21"
sys-locale = "0.3.1"
yaml-rust2 = "0.8.0"
clap = { version = "4.5.4", features = ["derive"] }
simplelog = "0.12.2"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
serde = "1.0.197"
validator = { version = "0.17.0", features = ["derive"] }
hcaptcha = "2.3.1"