[package]
name = "syncmiru-srv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
sqlx = "0.7.4"
axum = "0.7.5"
socketioxide = "0.12.0"
log = "0.4.21"
rust-i18n = "3.0.1"
