services:
  syncmiru:
    build:
      dockerfile: ./Dockerfile-syncmiru
      context: .
    container_name: syncmiru
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./keys:/usr/src/app/keys:ro
      - ./config.yaml:/usr/src/app/config.yaml:ro
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - db:/var/lib/postgresql/data

  caddy:
      image: caddy:2
      container_name: caddy
      ports:
        - 80:80
      restart: unless-stopped
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro

  openresty:
    build:
      dockerfile: ./Dockerfile-openresty
      context: .
    container_name: openresty
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./openresty/sites:/etc/nginx/conf.d:ro
      - ./openresty/keys:/etc/openresty/keys:ro
      - ./openresty/lua-scripts:/etc/openresty/lua-scripts:ro
      - ./openresty/www-root:/var/www/openresty.localhost
      - ./openresty/.htpasswd-openresty.localhost:/etc/openresty/.htpasswd-openresty.localhost

volumes:
  db: